"""users table

Revision ID: 5324721bb107
Revises: 8c1a175a4b2a
Create Date: 2022-07-24 20:04:34.268223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5324721bb107'
down_revision = '8c1a175a4b2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.drop_column('user', 'last_login')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login', sa.DATETIME(), nullable=True))
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###
